-- ~/.config/nvim/lua/plugins.lua

return require("lazy").setup({
	require("plugins.snacks"),
	require("plugins.plenary"),
	require("plugins.telescope"),
	require("plugins.telescope-file-browser"),
	require("plugins.lazygit"),
	require("plugins.mason"),
	require("plugins.mason-lspconfig"),
	require("plugins.mason-null-ls"),
	require("plugins.nvim-autopairs"),
	require("plugins.bufferline"),
	require("plugins.conform"),
	require("plugins.nvim-web-devicons"),
	require("plugins.trouble"),
	require("plugins.nvim-treesitter"),
	require("plugins.harpoon"),
	require("plugins.nvim-lsp-ts-utils"),
	require("plugins.nvim-lspconfig"),
	require("plugins.gitsigns"),
	require("plugins.lualine"),
	require("plugins.autocomplete"),
	require("plugins.onedark"),
	require("plugins.playground"),
	require("plugins.copilot"),
	require("plugins.markview"),
})
