-- ~/.config/nvim/lua/plugins.lua

return require("lazy").setup({
  require("plugins.snacks"),
  require("plugins.snacks-picker"),
  require("plugins.plenary"),
  require("plugins.telescope"),
  -- require("plugins.telescope-file-browser"),
  require("plugins.lazygit"),
  require("plugins.mason"),
  require("plugins.nvim-autopairs"),
  require("plugins.bufferline"),
  require("plugins.conform"),
  require("plugins.nvim-web-devicons"),
  -- require("plugins.trouble"),
  require("plugins.nvim-treesitter"),
  -- require("plugins.harpoon"),
  -- require("plugins.nvim-lsp-ts-utils"),
  require("plugins.nvim-lspconfig"),
  require("plugins.gitsigns"),
  require("plugins.lualine"),
  require("plugins.autocomplete"),
  require("plugins.onedark"),
  -- require("plugins.catppuccin"),
  -- require("plugins.playground"),
  require("plugins.luasnip"),
  require("plugins.nvim-tree"),
  -- require("plugins.toggleterm"),
  -- require("plugins.dadbod"),
  -- require("plugins.goose"),
  require("plugins.vim-surround"),
  -- require("plugins.nvim-dap"),
  -- require("plugins.error_lens"),
  require("plugins.symbols-outline"),
  require("plugins.vim-visual-multi"),
    -- require("plugins.mason-lspconfig"),
    -- require("plugins.nvim-jdtls"),
    -- require("plugins.markview"),
})
