-- ~/.config/nvim/lua/plugins.lua

return require("lazy").setup({
    require("plugins.snacks"),
    require("plugins.snacks-picker"),
    require("plugins.plenary"),
    require("plugins.telescope"),
    require("plugins.lazygit"),
    require("plugins.mason"),
    require("plugins.nvim-autopairs"),
    require("plugins.bufferline"),
    require("plugins.conform"),
    require("plugins.nvim-lint"),
    require("plugins.nvim-web-devicons"),
    require("plugins.nvim-treesitter"),
    require("plugins.nvim-lspconfig"),
    require("plugins.gitsigns"),
    require("plugins.lualine"),
    require("plugins.autocomplete"),
    require("plugins.onedark"),
    require("plugins.luasnip"),
    require("plugins.nvim-tree"),
    require("plugins.vim-surround"),
    require("plugins.symbols-outline"),
    require("plugins.vim-visual-multi"),

    require("plugins.store-nvim"),
    require("plugins.cursor-ai-replacement"),


    -- commented pluings
    -- require("plugins.telescope-file-browser"),
    -- require("plugins.trouble"),
    -- require("plugins.harpoon"),
    -- require("plugins.nvim-lsp-ts-utils"),
    -- require("plugins.toggleterm"),
    -- require("plugins.dadbod"),
    -- require("plugins.goose"),
    require("plugins.nvim-dap"),
    -- require("plugins.error_lens"),
    -- require("plugins.catppuccin"),
    -- require("plugins.playground"),
    -- require("plugins.mason-lspconfig"),
    require("plugins.nvim-java"),
    -- require("plugins.markview"),
})
